server:
  port: 8080
spring:
  application:
    name: softtek
  datasource:
    url: jdbc:h2:mem:softtek
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true